//! Typed model of Skript's `docs.json`.
//!
//! The file is generated by `ch.njol.skript.doc.JSONGenerator` and published at
//! <https://docs.skriptlang.org/docs.json>. Schema version 2.0 carries 1,208
//! entries and 2,117 patterns for Skript 2.16.
//!
//! Every field is `#[serde(default)]` on purpose. The schema is generated from
//! Java annotations and drifts between releases — a new Skript version adding a
//! field, or an addon's generated dump omitting one, must not stop the language
//! server from starting. A missing field degrades one hover card; a hard
//! deserialisation error degrades everything.

use std::collections::HashMap;

use serde::Deserialize;

/// Accepts an explicit `null` wherever a value is expected, yielding the
/// default instead.
///
/// `#[serde(default)]` only covers a **missing** key. Skript's generator emits
/// `null` liberally — 1,050 entries have `"requirements": null`, 771 have
/// `"events": null`, and `patterns`, `examples`, `description`, `eventValues`
/// and `since` all do it too — so every field that can be null needs this as
/// well as `default`, or deserialising the real file fails outright.
fn nullable<'de, D, T>(deserializer: D) -> Result<T, D::Error>
where
    D: serde::Deserializer<'de>,
    T: Deserialize<'de> + Default,
{
    Ok(Option::<T>::deserialize(deserializer)?.unwrap_or_default())
}

/// Accepts a string, an array of strings, or `null`, always yielding a list.
///
/// The generator is inconsistent per field and per category: `description` is
/// an array on 1,207 entries but a bare string on 14; `keywords` is an array on
/// 39 and `null` on 992; `patterns` is `null` on 42. Modelling each as a plain
/// `Vec<String>` makes the real file fail to deserialise entirely.
fn string_list<'de, D>(deserializer: D) -> Result<Vec<String>, D::Error>
where
    D: serde::Deserializer<'de>,
{
    #[derive(Deserialize)]
    #[serde(untagged)]
    enum OneOrMany {
        One(String),
        Many(Vec<String>),
    }

    Ok(match Option::<OneOrMany>::deserialize(deserializer)? {
        None => Vec::new(),
        Some(OneOrMany::One(value)) => vec![value],
        Some(OneOrMany::Many(values)) => values,
    })
}

/// The whole database.
#[derive(Debug, Clone, Default, Deserialize)]
pub struct Docs {
    #[serde(default)]
    pub source: Source,

    #[serde(default, deserialize_with = "nullable")]
    pub conditions: Vec<Entry>,
    #[serde(default, deserialize_with = "nullable")]
    pub effects: Vec<Entry>,
    #[serde(default, deserialize_with = "nullable")]
    pub expressions: Vec<Entry>,
    #[serde(default, deserialize_with = "nullable")]
    pub events: Vec<Entry>,
    #[serde(default, deserialize_with = "nullable")]
    pub structures: Vec<Entry>,
    #[serde(default, deserialize_with = "nullable")]
    pub sections: Vec<Entry>,
    #[serde(default, deserialize_with = "nullable")]
    pub types: Vec<Entry>,
    #[serde(default, deserialize_with = "nullable")]
    pub functions: Vec<Entry>,
    #[serde(default, deserialize_with = "nullable")]
    pub experiments: Vec<Entry>,
    /// Published since Skript 2.13. Absent from older archives, hence the
    /// default rather than a hard requirement.
    #[serde(default, deserialize_with = "nullable")]
    pub properties: Vec<Entry>,
}

#[derive(Debug, Clone, Default, Deserialize)]
pub struct Source {
    #[serde(default)]
    pub name: String,
    /// The Skript version this database was generated from, e.g. `2.16.1`.
    #[serde(default)]
    pub version: String,
}

/// Which kind of syntax an entry describes.
///
/// This is the distinction the tree-sitter grammar provably cannot make, and
/// the reason the language server exists.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Category {
    Condition,
    Effect,
    Expression,
    Event,
    Structure,
    Section,
    Type,
    Function,
    Experiment,
    /// Property expressions, published since Skript 2.13.
    Property,
}

impl Category {
    pub const ALL: &'static [Category] = &[
        Category::Condition,
        Category::Effect,
        Category::Expression,
        Category::Event,
        Category::Structure,
        Category::Section,
        Category::Type,
        Category::Function,
        Category::Experiment,
        Category::Property,
    ];

    /// The LSP semantic token type this category maps to. These names are
    /// matched by `extension/languages/skript/semantic_token_rules.json`.
    pub fn semantic_token_type(self) -> &'static str {
        match self {
            Category::Condition => "skriptCondition",
            Category::Effect => "skriptEffect",
            Category::Expression => "skriptExpression",
            Category::Event => "skriptEvent",
            Category::Section => "skriptSection",
            Category::Structure => "skriptStructure",
            Category::Type => "skriptType",
            Category::Function => "function",
            Category::Experiment => "skriptStructure",
            Category::Property => "skriptExpression",
        }
    }

    pub fn label(self) -> &'static str {
        match self {
            Category::Condition => "condition",
            Category::Effect => "effect",
            Category::Expression => "expression",
            Category::Event => "event",
            Category::Structure => "structure",
            Category::Section => "section",
            Category::Type => "type",
            Category::Function => "function",
            Category::Experiment => "experiment",
            Category::Property => "property",
        }
    }
}

/// One documented syntax element.
#[derive(Debug, Clone, Default, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entry {
    #[serde(default)]
    pub id: String,
    #[serde(default)]
    pub name: String,

    /// `since` is an array for most categories but a bare string for types, so
    /// it is normalised on the way in.
    #[serde(default, deserialize_with = "nullable")]
    pub since: StringOrVec,

    #[serde(default, deserialize_with = "nullable")]
    pub deprecated: Deprecated,

    #[serde(default, deserialize_with = "string_list")]
    pub description: Vec<String>,
    #[serde(default, deserialize_with = "string_list")]
    pub patterns: Vec<String>,
    #[serde(default, deserialize_with = "string_list")]
    pub examples: Vec<String>,

    /// Server or plugin versions this syntax needs, e.g. `["Minecraft 1.16+"]`
    /// or `["Vault"]`. Free text with no grammar: prefixes vary between
    /// `Minecraft`, `MC`, `Spigot`, `Paper` and nothing at all.
    ///
    /// This is an **array** in every published database. It was modelled as a
    /// string until 2026-08-06, which made `Docs::parse` fail outright on the
    /// real file and silently fall back to the built-in catalog.
    #[serde(default, deserialize_with = "string_list")]
    pub requirements: Vec<String>,

    /// Expressions declare what they evaluate to.
    #[serde(default)]
    pub returns: Option<Reference>,

    /// Events expose `event-block`, `event-player`, … values.
    #[serde(default, deserialize_with = "nullable")]
    pub event_values: Vec<Reference>,

    /// Events this syntax is restricted to.
    #[serde(default, deserialize_with = "nullable")]
    pub events: Vec<Reference>,

    #[serde(default)]
    pub cancellable: bool,

    /// Search aliases. An **array** on every entry that has any, and `null`
    /// on the 992 that do not — never the string this was first modelled as.
    #[serde(default, deserialize_with = "string_list")]
    pub keywords: Vec<String>,

    /// Which addon registered this syntax. `None` is core Skript.
    ///
    /// Not part of any published schema — it is attached by the provider that
    /// loaded the entry, so a merged catalog can say where each line came from.
    #[serde(skip)]
    pub addon: Option<AddonRef>,

    /// The Skript version this element first appeared in, parsed from `since`.
    ///
    /// Cached here because `since` is free text and parsing it per completion
    /// item would be wasteful. `None` means the text carried no number at all
    /// (`"unknown (before 2.1)"`), which is treated as always available.
    #[serde(skip)]
    pub min_version: Option<crate::version::Version>,
}

impl Entry {
    pub fn is_deprecated(&self) -> bool {
        self.deprecated.is_deprecated()
    }

    /// Where this syntax came from, for display.
    pub fn provider(&self) -> &str {
        match &self.addon {
            Some(addon) => &addon.name,
            None => "Skript",
        }
    }

    /// True when this element needs a newer Skript than `target`.
    ///
    /// Entries whose `since` carried no number are never considered too new —
    /// they all predate 2.2.
    pub fn needs_newer_than(&self, target: crate::version::Version) -> bool {
        self.min_version.is_some_and(|min| min > target)
    }
}

/// Which addon a syntax element came from.
///
/// `None` means core Skript. Skript's own `docs.json` never carries this — one
/// generated file describes exactly one addon and names it only at the root —
/// so it is filled in by whichever provider produced the entry.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct AddonRef {
    pub name: String,
    /// Where the addon lives, for the hover link. Hosts vary wildly (GitHub,
    /// SpigotMC, Modrinth, dev.bukkit.org), so this is for display only and is
    /// never used as a key — `name` is the join key.
    pub url: String,
    /// The addon version this syntax first appeared in, when known.
    pub since_version: Option<String>,
}

/// A `{ "id": …, "name": … }` cross-reference.
#[derive(Debug, Clone, Default, Deserialize)]
pub struct Reference {
    #[serde(default)]
    pub id: String,
    #[serde(default)]
    pub name: String,
}

impl Reference {
    /// Event values often have an empty `name`, in which case the id is the
    /// only thing worth showing.
    pub fn display(&self) -> &str {
        if self.name.is_empty() {
            &self.id
        } else {
            &self.name
        }
    }
}

/// `deprecated` is a bool in most entries but occasionally carries the
/// replacement text instead.
#[derive(Debug, Clone, Default, Deserialize)]
#[serde(untagged)]
pub enum Deprecated {
    #[default]
    Absent,
    Flag(bool),
    Note(String),
    Notes(Vec<String>),
}

impl Deprecated {
    pub fn is_deprecated(&self) -> bool {
        match self {
            Deprecated::Absent => false,
            Deprecated::Flag(flag) => *flag,
            Deprecated::Note(note) => !note.is_empty(),
            Deprecated::Notes(notes) => !notes.is_empty(),
        }
    }

    /// The replacement guidance, when the entry carries any.
    pub fn note(&self) -> Option<String> {
        match self {
            Deprecated::Note(note) if !note.is_empty() => Some(note.clone()),
            Deprecated::Notes(notes) if !notes.is_empty() => Some(notes.join(" ")),
            _ => None,
        }
    }
}

/// Normalises the `since` field, which the generator emits inconsistently.
#[derive(Debug, Clone, Default, Deserialize)]
#[serde(untagged)]
pub enum StringOrVec {
    #[default]
    Absent,
    One(String),
    Many(Vec<String>),
}

impl StringOrVec {
    pub fn first(&self) -> Option<&str> {
        match self {
            StringOrVec::Absent => None,
            StringOrVec::One(value) => Some(value),
            StringOrVec::Many(values) => values.first().map(String::as_str),
        }
    }

    pub fn joined(&self) -> String {
        match self {
            StringOrVec::Absent => String::new(),
            StringOrVec::One(value) => value.clone(),
            StringOrVec::Many(values) => values.join(", "),
        }
    }
}

impl Docs {
    pub fn parse(json: &str) -> Result<Self, serde_json::Error> {
        serde_json::from_str(json)
    }

    pub fn entries(&self, category: Category) -> &[Entry] {
        match category {
            Category::Condition => &self.conditions,
            Category::Effect => &self.effects,
            Category::Expression => &self.expressions,
            Category::Event => &self.events,
            Category::Structure => &self.structures,
            Category::Section => &self.sections,
            Category::Type => &self.types,
            Category::Function => &self.functions,
            Category::Experiment => &self.experiments,
            Category::Property => &self.properties,
        }
    }

    /// Every entry paired with its category.
    pub fn all(&self) -> impl Iterator<Item = (Category, &Entry)> {
        Category::ALL
            .iter()
            .flat_map(move |category| self.entries(*category).iter().map(move |e| (*category, e)))
    }

    pub fn total_entries(&self) -> usize {
        Category::ALL
            .iter()
            .map(|category| self.entries(*category).len())
            .sum()
    }

    pub fn total_patterns(&self) -> usize {
        self.all().map(|(_, entry)| entry.patterns.len()).sum()
    }

    /// Folds another database into this one, keeping the entry already present
    /// whenever both describe the same `id`.
    ///
    /// Order therefore encodes trust: merge Skript's official database first
    /// and SkriptHub second, and SkriptHub's own 1,237 copies of core Skript
    /// syntax lose to the authoritative ones. They really do collide — both
    /// sides use ids like `ExprVersion`.
    pub fn merge(&mut self, other: Docs) {
        for category in Category::ALL.iter().copied() {
            let seen: std::collections::HashSet<String> = self
                .entries(category)
                .iter()
                .filter(|entry| !entry.id.is_empty())
                .map(|entry| entry.id.to_ascii_lowercase())
                .collect();

            let incoming: Vec<Entry> = other
                .entries(category)
                .iter()
                .filter(|entry| {
                    entry.id.is_empty() || !seen.contains(&entry.id.to_ascii_lowercase())
                })
                .cloned()
                .collect();

            self.entries_mut(category).extend(incoming);
        }
    }

    /// Appends an entry to a category.
    pub fn push(&mut self, category: Category, entry: Entry) {
        self.entries_mut(category).push(entry);
    }

    fn entries_mut(&mut self, category: Category) -> &mut Vec<Entry> {
        match category {
            Category::Condition => &mut self.conditions,
            Category::Effect => &mut self.effects,
            Category::Expression => &mut self.expressions,
            Category::Event => &mut self.events,
            Category::Structure => &mut self.structures,
            Category::Section => &mut self.sections,
            Category::Type => &mut self.types,
            Category::Function => &mut self.functions,
            Category::Experiment => &mut self.experiments,
            Category::Property => &mut self.properties,
        }
    }

    /// Fills in each entry's cached `min_version` from its `since` text.
    pub fn resolve_versions(&mut self) {
        for category in Category::ALL.iter().copied() {
            for entry in self.entries_mut(category) {
                entry.min_version = crate::version::parse_since(&entry.since.joined());
            }
        }
    }

    /// Every distinct addon represented in this database.
    pub fn addons(&self) -> Vec<AddonRef> {
        let mut seen: Vec<AddonRef> = Vec::new();
        for (_, entry) in self.all() {
            if let Some(addon) = &entry.addon {
                if !seen.iter().any(|known| known.name == addon.name) {
                    seen.push(addon.clone());
                }
            }
        }
        seen
    }

    /// Type names indexed by lowercase name, for resolving `%type%` slots.
    pub fn types_by_name(&self) -> HashMap<String, &Entry> {
        self.types
            .iter()
            .map(|entry| (entry.name.to_ascii_lowercase(), entry))
            .collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn accepts_since_as_a_string_or_an_array() {
        let one: Entry = serde_json::from_str(r#"{"since": "1.0"}"#).unwrap();
        assert_eq!(one.since.first(), Some("1.0"));

        let many: Entry = serde_json::from_str(r#"{"since": ["2.10", "2.11"]}"#).unwrap();
        assert_eq!(many.since.joined(), "2.10, 2.11");

        let absent: Entry = serde_json::from_str("{}").unwrap();
        assert_eq!(absent.since.first(), None);
    }

    #[test]
    fn accepts_deprecated_as_a_flag_or_a_note() {
        let flag: Entry = serde_json::from_str(r#"{"deprecated": true}"#).unwrap();
        assert!(flag.is_deprecated());

        let note: Entry = serde_json::from_str(r#"{"deprecated": "use X instead"}"#).unwrap();
        assert!(note.is_deprecated());
        assert_eq!(note.deprecated.note().as_deref(), Some("use X instead"));

        let absent: Entry = serde_json::from_str("{}").unwrap();
        assert!(!absent.is_deprecated());
    }

    #[test]
    fn an_unknown_field_does_not_break_deserialisation() {
        // A future Skript release must not stop the server from starting.
        let entry: Entry =
            serde_json::from_str(r#"{"id": "X", "somethingNew": {"a": 1}}"#).unwrap();
        assert_eq!(entry.id, "X");
    }

    #[test]
    fn a_missing_category_yields_an_empty_slice() {
        let docs = Docs::parse("{}").unwrap();
        assert!(docs.entries(Category::Effect).is_empty());
        assert_eq!(docs.total_entries(), 0);
    }
}
